/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.File;
import java.io.IOException;

public class App {
    
    private final Game game;

    public App() {
        this.game = new Game();
    }

    public App(File gameFile) throws Exception {
        this.game = Game.from(gameFile);
    }

    public void run() throws Exception {
        game.play();
    }

    public String getGreeting() {
        return "Welcome to Tic-Tac-Toe!";
    }

    public static void main(String[] args) throws Exception {
        App app;
        if (args.length > 0) {
            app = new App(new File(args[0]));
        } else {
            app = new App();
        }
        System.out.println(app.getGreeting());
        app.run();
    }
}
