/*
 * This source file was generated by the Gradle 'init' task
 */
package org.xxdc.oss.example;

import static org.testng.Assert.*;

import org.testng.annotations.*;

public class AppTest {
  @Test
  public void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }
}
